# Generated by Django 5.1.2 on 2024-10-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_delete_testmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='path',
        ),
    ]
